version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
 seleniumhub:
  image: selenium/hub
  restart: always
  ports:
    - "4444:4444"
  networks:
    - prodnetwork
 chrome:
  image: selenium/node-chrome-debug
  restart: always
  ports:
    - "5900:5900"
  depends_on:
    - seleniumhub
  environment:
    - HUB_PORT_4444_TCP_ADDR=seleniumhub
    - HUB_PORT_4444_TCP_PORT=4444
  networks:
    - prodnetwork
